version: '3'

services:
  scraper:
    build: ./app
    volumes: 
      - ./app:/app
    network_mode: "container:gluetun_scraper"
    restart: on-failure:2
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York